---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: gha-cluster
  region: us-west-2
nodeGroups:
  - name: github-workers
    instanceType: t3.medium
    desiredCapacity: 6
    minSize: 4
    maxSize: 10
    ssh:
      allow: true
      publicKeyName: aarifs-access-key
